site_name: ROKAM

theme:
  name: material
  logo: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    - header.autohide
  language: en
  palette:
    - scheme: slate        # Default: dark mode first
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: indigo
      accent: cyan
    - scheme: default      # Secondary: light mode
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: blue
      accent: red

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/google
      link: https://rokam.co
  favicon: assets/images/favicon.ico

extra_css:
  - assets/extra.css

copyright: |
  &copy; 2024 <a href="https://github.com/rokamtechnology" target="_blank" rel="noopener">ROKAM</a>
